export enum TimeOffRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  FAILED_SYNC = 'FAILED_SYNC',
}

export enum BalanceSyncEventType {
  REALTIME_PULL = 'REALTIME_PULL',
  REALTIME_PUSH = 'REALTIME_PUSH',
  BATCH_IMPORT = 'BATCH_IMPORT',
  RECONCILIATION = 'RECONCILIATION',
}

export enum HcmFailureMode {
  NORMAL = 'NORMAL',
  TIMEOUT = 'TIMEOUT',
  ERROR = 'ERROR',
}

export enum HcmValidationMode {
  NORMAL = 'NORMAL',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  INVALID_COMBINATION = 'INVALID_COMBINATION',
  BROKEN = 'BROKEN',
}
